message("zigbee_rcp_app.cmake: ZC_EXE: ${ZC_EXE} -> zc_exe: ${zc_exe} with zc_src: ${zc_src}")
message("zigbee_rcp_app.cmake: ZR_EXE: ${ZR_EXE} -> zr_exe: ${zr_exe} with zr_src: ${zr_src}")
message("zigbee_rcp_app.cmake: ZED_EXE: ${ZED_EXE} -> zed_exe: ${zed_exe} with zed_src: ${zed_src}")
message("")
if(ZC_EXE)
    message("zigbee_rcp_app.cmake: ZC_EXE: ${ZC_EXE} -> zc_exe: ${zc_exe} with zc_src: ${zc_src}")
    add_executable(${zc_exe} ${zc_src})
    set_target_properties(${zc_exe} PROPERTIES COMPILE_FLAGS "-O3 -s -DZB_COORDINATOR_ROLE -DZB_ROUTER_ROLE" )
    target_link_libraries(${zc_exe} LINK_PUBLIC libzboss.a libreadline.so)
    install(TARGETS ${zc_exe} DESTINATION bin)
endif(ZC_EXE)

if(ZR_EXE)
    message("zigbee_rcp_app.cmake: ZR_EXE: ${ZR_EXE} -> zr_exe: ${zr_exe} with zr_src: ${zr_src}")
    add_executable(${zr_exe} ${zr_src})
    set_target_properties(${zr_exe} PROPERTIES COMPILE_FLAGS "-O3 -s -DZB_ROUTER_ROLE" )
    target_link_libraries(${zr_exe} LINK_PUBLIC libzboss.a libreadline.so)
    install(TARGETS ${zr_exe} DESTINATION bin)
endif(ZR_EXE)

if(ZED_EXE)
    message("zigbee_rcp_app.cmake: ZED_EXE: ${ZED_EXE} -> zed_exe: ${zed_exe} with zed_src: ${zed_src}")
    add_executable(${zed_exe} ${zed_src})
    set_target_properties(${zed_exe} PROPERTIES COMPILE_FLAGS "-O3 -s -DZB_ED_ROLE" )
    target_link_libraries(${zed_exe} LINK_PUBLIC libzboss.ed.a libreadline.so)
    install(TARGETS ${zed_exe} DESTINATION bin)
endif(ZED_EXE)

unset(ZC_EXE CACHE)
unset(ZR_EXE CACHE)
unset(ZED_EXE CACHE)

message("")
message("zigbee_rcp_app.cmake: ZC_EXE: ${ZC_EXE} -> zc_exe: ${zc_exe} with zc_src: ${zc_src}")
message("zigbee_rcp_app.cmake: ZR_EXE: ${ZR_EXE} -> zr_exe: ${zr_exe} with zr_src: ${zr_src}")
message("zigbee_rcp_app.cmake: ZED_EXE: ${ZED_EXE} -> zed_exe: ${zed_exe} with zed_src: ${zed_src}")
message("")
message("")

